trigger:
  batch: true
  branches:
    include:
      - master

variables:
  - name: imageName
    value: ps-terraform-agent
  - name: terraformVersion
    value: 0.12.13

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Ubuntu1804
        displayName: terraform docker image build (Ubuntu 1804)

        pool:
          vmImage: ubuntu-latest

        steps:
        - task: Docker@2
          displayName: buildAndPush
          inputs:
            containerRegistry: 'rdbartram-docker'
            repository: dftai/ps-terraform-agent
            command: buildAndPush
            Dockerfile: 'ubuntu1804/Dockerfile'
            buildContext: 'ubuntu1804'
            arguments: 'TERRAFORM_VERSION=$(terraformVersion)'
            tags: |
              ubuntu1804
              ubuntu1804-$(terraformVersion)
              latest
      
      - job: Windows
        displayName: terraform docker image build (Windows)

        pool:
          vmImage: windows-latest

        steps:
        - task: Docker@2
          displayName: buildAndPush
          inputs:
            containerRegistry: 'rdbartram-docker'
            repository: dftai/ps-terraform-agent
            command: buildAndPush
            Dockerfile: 'windows/Dockerfile'
            buildContext: 'windows'
            arguments: 'TERRAFORM_VERSION=$(terraformVersion)'
            tags: |
              windows
              windows-$(terraformVersion)
              latest
